from enum import Enum

class EnumCargos(Enum):
    AGENTE_DE_RESERVAS = 1
    AGENTE_DE_ATENDIMENTO_AO_CLIENTE = 2
    SUPERVISOR_DE_OPERACOES_DE_RESERVAS = 3
    GERENTE_DE_VENDAS = 4

class EnumGenero(Enum):
    MASCULINO = 1
    FEMININO = 2
    NAO_BINARIO = 3
    AGENERO = 4
    GENDERQUEER = 5
    OUTRO = 6
    PREFIRO_NAO_INFORMAR = 7

class EnumClasseVoo(Enum):
    ECONOMICA = 1
    EXECUTIVA = 2
    PRIMEIRA_CLASSE = 3
    CLASSE_BUSINESS = 4
    CLASSE_ECONOMICA_SUPERIOR = 5

class EnumStatusVoo(Enum):
    AGENDADO = 1
    EM_ANDAMENTO = 2
    ATRASADO = 3
    CANCELADO = 4
    CONCLUIDO = 5