# Generated by Django 5.1.2 on 2024-12-03 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aviao',
            name='voo',
        ),
        migrations.RemoveField(
            model_name='piloto',
            name='voo',
        ),
        migrations.AddField(
            model_name='voo',
            name='aviao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.aviao', verbose_name='Avião'),
        ),
        migrations.AddField(
            model_name='voo',
            name='piloto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.piloto', verbose_name='Piloto'),
        ),
    ]
