# Generated by Django 5.1.2 on 2024-10-22 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voo',
            name='aviao',
        ),
        migrations.RemoveField(
            model_name='voo',
            name='piloto',
        ),
        migrations.AddField(
            model_name='aviao',
            name='voo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.voo', verbose_name='Voo'),
        ),
        migrations.AddField(
            model_name='piloto',
            name='voo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.voo', verbose_name='Voo'),
        ),
    ]
