# Generated by Django 5.1.2 on 2024-10-31 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_voo_aviao_remove_voo_piloto_aviao_voo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='user_permissions',
        ),
    ]
